### ISSUE TITLE
type spec format `M:F/#` removed in OTP 19

### ISSUE THREAD

**Issue by tsloughter** [hyperthunk/hamcrest-erlang#20]
Type specs like `-spec(will_fail/0 :: () -> hamcrest:matchspec()).` no longer exist in OTP 19, so hamcrest fails to build.

**Comment by hyperthunk** [comment]
Hmmm, okay let me have a think about fixing that

**Comment by silviucpp** [comment]
Fix it by changing into:

-spec(will_fail() -> hamcrest:matchspec()).

Silviu
